name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install deps
      run: sudo apt-get install xutils-dev libx11-dev libxext-dev
    - name: Imake
      run: xmkmf
    - name: Imake patch for Linux
      run: sed -i 's/-D_BSD_SOURCE -D_SVID_SOURCE/-D_DEFAULT_SOURCE/g' Makefile
    - name: make clean
      run: make clean
    - name: make
      run: make
